version: 2.1

jobs:
  docker_build:
    working_directory: ~/rpm
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: Dependencies
          command: mkdir -p /opt && yum -y install make
      - run:
          name: Build haproxy
          command: make build RELEASE=$CIRCLE_BUILD_NUM
      - run:
          name: Test install and Prometheus
          command: make run-tests RELEASE=$CIRCLE_BUILD_NUM
      - persist_to_workspace:
          root: rpmbuild
          paths:
            - RPMS
            - SRPMS
  publish:
    working_directory: ~/rpm
    docker:
      - image: circleci/ruby:2.6-stretch
    steps:
      - attach_workspace:
          at: ~/rpm/rpmbuild
      - run:
          name: Install package_cloud CLI tool
          command: gem install package_cloud
      - run:
          name: Publish rpms
          command: package_cloud push till/pngmbh-oss/el/7 ./rpmbuild/RPMS/x86_64/*.rpm
      - run:
          name: Publish srpms
          command: package_cloud push till/pngmbh-oss/el/7 ./rpmbuild/SRPMS/*.rpm

workflows:
  test:
    jobs:
      - docker_build
  publish:
    jobs:
      - docker_build:
          filters:
            branches:
              only: pngmbh-2.0
      - publish:
          context: packagecloud
          requires:
            - docker_build
          filters:
            branches:
              only: pngmbh-2.0

